### PR TITLE
General improvements to CommentsParser

### PR DESCRIPTION
**Pull request by vasilionjea**

### CODE REVIEW

**Comment by Glavin001** [comment]
Should we use @sindresorhus's  https://github.com/sindresorhus/get-urls for retrieving URLs from the comments string?

**Comment by vasilionjea** [comment]
Feel free to send a pull request if you think it'd be better.

**Comment by Glavin001** [comment]
I'm not really sure; I was hoping @sindresorhus would be able to describe the benefits and if he think it's worth while. Just noticed it in my feed. 

One thing that is interesting and useful is that it would " normalized and uniquified" the URLs. Is that something that is already being done with your commentParser? And do we need it? Will the various music service's API care if our URLs are not normalized?

I will take a closer look and of course make a PR if it's worth while. Your script is working well, and quick as is, so it is a likely unnecessary change.

**Comment by vasilionjea** [comment]
I think whether it proves to be an issue or not, URL normalization is definitely worth doing. I would think it would be a good practice in general.

As for making the URLs unique, with Underscore it's as easy as `_.uniq(array);`... but yeah I haven't done that yet.

**Comment by sindresorhus** [comment]
I don't care either way, but I definitely think we shouldn't reinvent the wheel. Use small reusable libs instead of doing it yourself ;)

**Comment by vasilionjea** [comment]
I'm open to using any libs out there as long as we define why we're using x option -vs- y option. Either way the main goal is to build an awesome/useful app, so personally I don't care.

**Comment by sindresorhus** [comment]
@vasilionjea modularity and NIH

**Comment by vasilionjea** [comment]
NIH?

**Comment by sindresorhus** [comment]
@vasilionjea Not Invented Here (google it)

**Comment by Glavin001** [comment]
Would @sindresorhus or @addyosmani be able to merge this PR when they get a chance?

I'm hopefully going to have time tonight to get one of the players working -- probably start with SoundCloud (See #5). Then we will have something working to encourage developers to contribute to.

@sindresorhus, did you have a chance to look into publishing this to `gh-pages` branch or some other server? There's not much to see right now, however hopefully there will be soon.

**Comment by sindresorhus** [comment]
Landed :D

Will get it published later today.

**Comment by Glavin001** [comment]
Excellent, thank you!

**Comment by vasilionjea** [comment]
Thanks for the "google it" recommendation @sindresorhus! Now I know... LOL!

**Comment by sindresorhus** [comment]
@Glavin001 done: http://tastejs.com/TasteMusic/

**Comment by Glavin001** [comment]
Thanks, @sindresorhus!

**Pull request closed without merging**
